### ISSUE TITLE
Rename rules_python() to rules_python_init()

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel-federation#111]
Maybe it is just me, but names like `rules_python()` is really confusing.
It leads to the immediate questions:
- Am I already adding the rules?
- Why do I have to call `rules_python_setup()` afterwards?

My feeble little mind would be way more on board if it would be called: `rules_python_init`

**Comment by aiuto** [comment]
Naming is hard. No one is happy. The fact that we need to say
```
rules_foo()
load(..., rules_foo_setup)
rules_foo_setup()
```
is an ugly first cut.  We have to get it down to something close to

```
bazel_federation_require('rules_foo', 'rules_python', ...)
bazel_federtaion_init()
```

FWIW,  `rules_python_init()` is not a good name either. We are declaring a requirement, not actually doing the initialize.  This is one of the reasons we have to get it down to a list of repo names.
