### ISSUE TITLE
--incompatible_disallow_empty_glob

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-federation#117]
It looks like this package is not compatible with `--incompatible_disallow_empty_glob`.
Since many repositories depend on it, it would be great to update it quickly.

**Comment by laurentlb** [comment]
Breaking Skylib and other rules (whether it's for users or developers) is a blocker for me.

**Comment by aiuto** [comment]
cc @fweikert 
I can't figure out what we are actually testing in the federation CI.  I think we are not testing the user experience.

The best thing to do now is fix skylib to not depend on rules_pkg through the federation, then we can rebuild the federation and tests in a sensible way.
