### ISSUE TITLE
Bazel Federation failing on buildkite (bazel_skylib)

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel-federation#120]
Bazel federation is failing on buildkite for bazel@HEAD. Particularly, a bazel_skylib test is failing. It's tied to some CI changes (and not Bazel changes)

Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1609#ce13c59d-d31e-47e9-a9e9-1a0dbacd2616

This was fixed in bazel_skylib with https://github.com/bazelbuild/bazel-skylib/commit/68acaa5d6aa65e89d99ac775b3d895fea91a3bae

**Comment by aiuto** [comment]
@c-parsons Is skylib intended to be used at arbitrary github release or the numbered releases?

**Comment by meteorcloudy** [comment]
@aiuto The fix is already in bazel-skylib version 1.0.3, can we update bazel-skylib in the federation project?
