### ISSUE TITLE
Add rules_proto to federation

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel-federation#32]
It would be great if `rules_proto` is part of the federation. It's a dependency of `Protobuf` (starting with 3.9.1), and also soon used by most projects.

I tried to add it to `repositories.bzl` but failed because there is a, unfortunately unavoidable, dependency cycle between `rules_proto` and `Protobuf`. Is there any existing mechanism to resolve this issue?

**Comment by fweikert** [comment]
Currently we're still working on the basic structure of the federation, and our focus is on the most important projects (1. skylib, rules_cc, rules_java, rules_python, 2. rules_docker, stardoc and maybe rules_go). I'll add rules_proto to that list.

For now I want to learn more about the dependency cycle. Which of the following statements apply?

1. Developers who want to use protobuf in their projects need to add rules_proto to their WORKSPACE, too.
2. Protobuf needs rules_proto in its WORKSPACE for testing / releasing / whatever, but users of Protobuf don't need rules_proto.
3. Developers who want to use rules_proto in their projects need to add protobuf to their WORKSPACE, too.
4. rules_proto needs protobuf in its WORKSPACE for testing / releasing / whatever, but users of rules_proto don't need protobuf.

**Comment by Yannic** [comment]
Unfortunately, it's 1 and 3.

Protobuf requires rules_proto to declare e.g. `proto_lang_toolchain` for C++ and Java [1], and rules_proto requires Protobuf to perform the compilation (currently through native rules) [2].

[1] https://github.com/protocolbuffers/protobuf/blob/c60aaf79e63b911b2c04c04e1eacb4f3c36ef790/BUILD#L989
[2] https://github.com/bazelbuild/bazel/blob/c145f8eb1518d97cbaadb61003efa7ce710b559d/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoConfiguration.java#L71

**Comment by fweikert** [comment]
In this case we can get away with something like

```
def protobuf(include_rules_proto=True):
  if include_rules_proto:
    rules_proto(include_protobuf=False)
  [...]

def rules_proto(include_protobuf=True):
  if include_protobuf:
    protobuf(include_rules_proto=False)
  [...]
```

However, since it doesn't make sense to use one of the projects without the other, we could also expose a different function that simply fetches both repos, and make rules_proto() and protobuf() private (via the underscore prefix).

**Comment by hlopko** [comment]
(FWIW, rules_cc will grow a development dependency on rules_proto in internal change cl/274157396).

**Comment by Yannic** [comment]
Users of the federation cannot become compatible with `--incompatible_load_{cc,java,proto,python}_rules_from_bzl` without fixing this.

**Comment by fweikert** [comment]
Thanks for the update - I‘ll try to onboard rules_proto next week since I’m already looking into protobuf, too.
