### ISSUE TITLE
add rules_go to federation

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel-federation#60]
Need to resolve skylib 0.9.0 sets() breakage.

**Comment by aiuto** [comment]
obsolete so many things have moved on.

**Comment by achew22** [comment]
Is this to say that federation is not happening?

**Comment by aiuto** [comment]
It is only that this particular issue was too long obsolete. I am trying to
clear my personal backlog after having had some urgent issues in the last
few months.

We know we need a concept like the federation. Our current thinking is that
it is best served by principled changes to WORKSPACE semantics to make
supporting it easier. So, it is likely to need some core Bazel changes
first before we can make this work right.
