### ISSUE TITLE
Wrong download url in release notes of 0.0.1

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel-federation#76]
The WORKSPACE snipped in the release notes of 0.0.1 references an url that returns 404: https://github.com/bazelbuild/bazel_federation/releases/download/0.0.1/bazel_federation-0.0.1.tar.gz

The correct url should be https://github.com/bazelbuild/bazel-federation/releases/download/0.0.1/bazel_federation-0.0.1.tar.gz (`bazelbuild/bazel-federation` vs `bazelbuild/bazel_federation`).

**Comment by fweikert** [comment]
Thanks for the report! I only discovered this particular issue now, but I already fixed the underlying problem last week. The release notes should be fine now.
